[MIG] beesdoo_inventory: migrate to 12.0
beescoop/Obeesdoo pull request #111
Opened 2019-11-17 13:51 UTC by sdegueldre

This PR migrates the beesdoo_inventory module to odoo v12.0

2019-11-17 14:18 UTC, remytms requested changes
I know that many changes I requested is not from you but it's better to clean it know than never. :)

2019-11-17 14:18 UTC, remytms commented on beesdoo_inventory/__init__.py
> +from . import models
Missing end of line.

2019-11-17 14:18 UTC, remytms commented on beesdoo_inventory/__manifest__.py
> +    'name': "beesdoo_inventory",
Can you change it by: `Beesdoo Inventory`.

2019-11-17 14:18 UTC, remytms commented on beesdoo_inventory/__manifest__.py
> +        - SOO24 - Bon de livraison""",
Can you change this description to a better one ? :) Thanks.

2019-11-17 14:18 UTC, remytms commented on beesdoo_inventory/__manifest__.py
> +        - SOO24 - Bon de livraison""",
I mean changing summary, not the description that you can leave empty.

2019-11-17 14:18 UTC, remytms commented on beesdoo_inventory/__manifest__.py
> +}
Missing end of line.

2019-11-17 14:18 UTC, remytms commented on beesdoo_inventory/models/__init__.py
> +from . import stock
Missing end of line.

2019-11-17 14:18 UTC, remytms commented on beesdoo_inventory/views/stock.xml
> +<?xml version="1.0" encoding="utf-8"?>
Can you fix this file by replacing all tabs by 4 spaces. :)

2019-11-17 14:18 UTC, remytms commented on beesdoo_inventory/models/stock.py
> +from odoo import models, fields, api, _
Can you use `isort` to sort this import ? :)

2019-11-17 16:42 UTC, sdegueldre commented
Should be okay now @remytms

2019-11-17 19:05 UTC, remytms approved these changes
Thanks for the improvements ! :)

2020-01-17 15:03 UTC, remytms commented
@sdegueldre Same as here: https://github.com/beescoop/Obeesdoo/pull/114#issuecomment-575652417

2020-01-26 08:14 UTC, merged