12.0 mig beesdoo stock
beescoop/Obeesdoo pull request #130
Opened 2020-01-26 13:49 UTC by NadTr

2020-04-08 14:28 UTC, vvrossem requested changes
Hi @NadTr ! Thank you for you work on the migration :confetti_ball: 
Some changes to make on the `__manifest__.py` and on `stock_view.xml`

2020-04-08 14:28 UTC, vvrossem commented on beesdoo_stock/__manifest__.py
> +    'installable': False,
[Switch the installable key to True](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0#tasks-to-do-in-the-migration)

2020-04-10 11:28 UTC, vvrossem commented on beesdoo_stock/views/stock_view.xml
> +           <button name="do_new_transfer" position="after">
`do_new_transfer` is named `button_validate` in 12.0

2020-04-10 11:46 UTC, vvrossem commented
Hi @NadTr, I've noticed another change to make. Cheers :clinking_glasses:

2020-05-05 17:23 UTC, remytms commented
See #144

2020-05-05 17:23 UTC, closed without merging