[12.0] [MIG] compute_purchase_order
beescoop/Obeesdoo pull request #145
Opened 2020-04-16 15:24 UTC by vvrossem

2020-04-17 15:06 UTC, robinkeunen requested changes
Yo, je suis un peu gêné de te faire nettoyer mon mauvais code. Jpeux faire une passe dessus la semaine prochaine si tu veux.

2020-04-17 15:06 UTC, robinkeunen commented on compute_purchase_order/models/computed_purchase_order.py
> +        size=64,
peut être retiré

2020-04-17 15:06 UTC, robinkeunen commented on compute_purchase_order/models/computed_purchase_order.py
> +        record['date_planned'] = self._get_default_date_planned()
peut être calculé directement dans le _default_ de la définition du champs du modèle.

2020-04-17 15:06 UTC, robinkeunen commented on compute_purchase_order/models/computed_purchase_order.py
> +            cpol_ids.append(cpol.id)
inutile

2020-04-17 15:06 UTC, robinkeunen commented on compute_purchase_order/models/computed_purchase_order.py
> +            cpol.purchase_quantity = cpol.minimum_purchase_qty
directement dans le create.

2020-04-17 15:06 UTC, robinkeunen commented on compute_purchase_order/models/computed_purchase_order.py
> +        record['name'] = self._compute_default_name()
pareil que `date_planned`

2020-04-17 15:06 UTC, robinkeunen commented on compute_purchase_order/models/computed_purchase_order.py
> +            return suppliers.pop()
devrait retourner un record_set plutot qu'un id

2020-04-17 15:06 UTC, robinkeunen commented on compute_purchase_order/models/computed_purchase_order.py
> +        purchase_order = PurchaseOrder.create(po_values)
let purchase_order set default name and simplify with:

```
po = self.env['purchase.order'].create({
            'date_order': self.order_date,
            'partner_id': self.supplier_id.id,
            'date_planned': self.date_planned,
})

2020-04-17 15:06 UTC, robinkeunen commented on compute_purchase_order/models/computed_purchase_order.py
> +                pol = PurchaseOrderLine.create(pol_values)
same comment as for purchase order: 
- let lines be set by purchase.order.line default value
- simplify statement

```python
self.env['purchase.order.line'].create({
    'product_id': cpo_line.get_default_product_product().id,
    'product_qty': cpo_line.purchase_quantity,
    'price_unit': cpo_line.product_price,
    'product_uom': cpo_line.uom_po_id.id,
    'order_id': purchase_order.id,
    'date_planned': self.date_planned,
})
```

2020-04-17 15:06 UTC, robinkeunen commented on compute_purchase_order/models/computed_purchase_order_line.py
> +            )
can be replaced by `product_template.product_variant_id` set in `odoo.addons.product.models`

```python

class ProductTemplate(models.Model):
    _name = "product.template"
...
    product_variant_ids = fields.One2many('product.product', 'product_tmpl_id', 'Products', required=True)
    # performance: product_variant_id provides prefetching on the first product variant only
    product_variant_id = fields.Many2one('product.product', 'Product', compute='_compute_product_variant_id')
```

2020-04-17 15:06 UTC, robinkeunen commented on compute_purchase_order/models/computed_purchase_order_line.py
> +    @api.onchange('product_template_id')
no need for both `onchange` and `depends`

2020-04-17 15:06 UTC, robinkeunen commented on compute_purchase_order/models/computed_purchase_order_line.py
> +                raise ValidationError('Purchase quantity for {product_name} must be greater than 0'  # noqa
abusive `# noqa`

2020-04-17 15:06 UTC, robinkeunen commented on compute_purchase_order/models/computed_purchase_order_line.py
> +                raise ValidationError('Purchase quantity for {product_name} must be greater than 0'  # noqa
translate text

2020-04-17 15:06 UTC, robinkeunen commented on compute_purchase_order/models/product_template.py
> +            pt.main_supplier_id = sellers_ids and sellers_ids[0].name or False
Tain, parfois j'écris des trucs obscurs pour faire une ligne. Plus lisible si explicite:

```python
if seller_ids:
   pt.main_supplier_id = sellers_ids[0].name
else:
    pt.main_supplier_id = False
```

2020-04-17 15:06 UTC, robinkeunen commented
Anyway, merci pour le taff!

2020-05-06 20:11 UTC, remytms approved these changes

2020-05-06 20:11 UTC, remytms commented on purchase_order_generator/views/product_template.xml
> +      <!--<field name="inherit_id" ref="product.product_template_tree_view"/>-->
Je vais virer cette ligne avant de fusionner.

2020-05-06 20:21 UTC, merged