[12.0] [MIG] beesdoo_pos
beescoop/Obeesdoo pull request #146
Opened 2020-04-17 12:15 UTC by mclaeysb

I removed (together with their security and translation files)

- 'Bill Value' (standard in v12)
- 'Send Orders by email' (replace with OCA module)

Functionallity that's still in place:

- Displaying eaters on POS ActionpadWidget and PaymentScreenWidget (altought not functional anymore - @tfr-odoo or @vvrossem, could you take a look at this? My initial debugging didn't go further then checking that the spans's for this information`<span class="customer-delegate1"></span>` are in place and the `get_eater()` and `_get_eater()` function work, but somehow they are not called.)
- Some modification to `default_barcode_pattern.xml` encoding.

2020-04-17 12:58 UTC, vvrossem commented
@mclaeysb 
After installing `beesdoo_pos` and opening a POS session, the browser console shows a warning about `web.DataModel`:
![beesdoo_pos](https://user-images.githubusercontent.com/28013700/79571092-e4da3700-80ba-11ea-8d07-ed9ae3648a06.png)
It's deprecated and you need to use `web.rpc` instead:
- [Missing dependencies web.DataModel in odoo11](https://www.odoo.com/forum/help-1/question/missing-dependencies-web-datamodel-in-odoo11-133658) 
- [web.DataModel is missing odoo11](https://stackoverflow.com/questions/50403242/web-datamodel-is-missing-odoo11)

2020-04-20 08:18 UTC, remytms commented
@mclaeysb I think that @vvrossem is a better reviewer for this task.

2020-04-20 13:39 UTC, mclaeysb commented
Fixed, thanks @vvrossem for the help 🎉 !

2020-05-04 11:15 UTC, vvrossem requested changes
LGTM. Just some renaming to comply with OCA conventions

2020-05-04 11:15 UTC, vvrossem commented on beesdoo_pos/static/src/js/beesdoo.js
>  odoo.define('beescoop.pos', function (require) {
OCA convention is : module_name.type (type = screens / models / etc...)

In our case : `odoo.define('beesdoo_pos.screens', function (require) {...})`

2020-05-04 11:15 UTC, vvrossem commented on beesdoo_pos/static/src/js/beesdoo.js
>      var module   = require("point_of_sale.screens");
rename `module` occurrences in `screens`
`var screens = require("point_of_sale.screens");`

2020-05-04 11:15 UTC, vvrossem commented on beesdoo_pos/static/src/js/beesdoo.js
> +    var rpc = require('web.rpc')
I am unsure about this, but since we use `this._rpc`, `rpc` import can be removed

2020-05-05 16:20 UTC, merged