[12.0][ADD] beesdoo_posorder_amount: by year
beescoop/Obeesdoo pull request #177
Opened 2020-09-08 08:34 UTC by mclaeysb

Using `groupby()`!

2020-09-11 10:07 UTC, robinkeunen requested changes
Superb, glad to learn about groupby! I have strong opinions about naming though, as you know ;-)

2020-09-11 10:07 UTC, robinkeunen commented on beesdoo_website_posorder_amount/templates/portal_posorder_amount.xml
> +                <table class="table table-striped">
Name your xml elements.

2020-09-11 10:07 UTC, robinkeunen commented on beesdoo_website_posorder_amount/controllers/main.py
> +                owned_posorder, key=lambda element: element.date_order.year
better naming for better code ✊ 

```python
for key, group in groupby(
    owned_posorder, key=lambda pos_order: pos_order.date_order.year`
)
```

2020-09-11 10:07 UTC, robinkeunen commented on beesdoo_website_posorder_amount/controllers/main.py
> +                owned_posorder, key=lambda element: element.date_order.year
and even, to take Vincent's comment into account:

```py
        values["posorder_amount_by_year"] = [
            {
                "year": year,
                "amount": sum(pos_order.amount_total for pos_order in grouped_pos_orders),
            }
            for year, grouped_pos_orders in groupby(
                owned_posorder, key=lambda pos_order: pos_order.date_order.year
        )
    ]

```

2020-10-26 15:40 UTC, vvrossem commented
ok to merge?

2020-10-26 15:48 UTC, vvrossem approved these changes

2020-10-26 15:49 UTC, vvrossem commented
merging :) I see that Robin's requests were made

2020-10-26 15:49 UTC, merged