[12.0] beesdoo_account: validate invoice with negative total amount
beescoop/Obeesdoo pull request #185
Opened 2020-09-22 16:38 UTC by vvrossem

[Task](https://gestion.coopiteasy.be/web#id=5107&view_type=form&model=project.task)

2020-09-25 13:46 UTC, robinkeunen requested changes
J'ai fait une proposition de changement pour rendre le code un peu plus robuste. 

De plus, je me demande si ce bout de code a sa place dans beesdoo_account ou plutot dans `beesdoo_custom` voire dans `invoice_negative_amount`

2020-09-25 13:46 UTC, robinkeunen commented on beesdoo_account/__manifest__.py
> +        - Allow validating an invoice with a negative total amount
This could go in `description.rst`

2020-09-25 13:46 UTC, robinkeunen commented on beesdoo_account/models/account_invoice.py
> +        return super(AccountInvoice, self).action_invoice_open()
C'est un peu dangereux car tu casses la chaine d'héritage si l'utilisateur est dans le groupe. Pour mitiger le risque, tu pourrais soit

1. appeler `action_invoice_negative_amount_open` si le user est dans le groupe ET si le montant est négatif*. (mais ce n'est pas foolproof)
2. créer une note de crédit au vol (mais on dévie des specs)

\* cf définition de base
```python
    def action_invoice_open(self):
...
        if to_open_invoices.filtered(lambda inv: float_compare(inv.amount_total, 0.0, precision_rounding=inv.currency_id.rounding) == -1):
```

2020-09-25 13:46 UTC, robinkeunen commented on beesdoo_account/models/res_config.py
> +    )
t'es obligé de créer ce champs pour avoir accès au groupe dans le code? 🤔

2020-09-27 22:28 UTC, remytms commented
@robinkeunen @vvrossem  Désolé la review a été faite après la validation client. Je fusionne ceci, ça m'a l'air d'être modifiable si besoin par après.

2020-09-27 22:29 UTC, merged

2020-09-28 08:21 UTC, vvrossem commented on beesdoo_account/__manifest__.py
> +        - Allow validating an invoice with a negative total amount
done in new PR

2020-09-28 08:21 UTC, vvrossem commented on beesdoo_account/models/account_invoice.py
> +        return super(AccountInvoice, self).action_invoice_open()
bien vu! je prends l'option 1

2020-09-28 08:21 UTC, vvrossem commented on beesdoo_account/models/res_config.py
> +    )
inspiré de: 
- [`account_invoice_line_description`](https://github.com/OCA/account-invoicing/tree/12.0/account_invoice_line_description)
- [`purchase_order_line_description`](https://github.com/OCA/purchase-workflow/tree/12.0/purchase_order_line_description)

Je pense qu'il est obligatoire de créer ce champ pour configurer le module soit au niveau de l'utilisateur, soit au niveau plus global des paramètres de configuration

2020-09-28 08:22 UTC, vvrossem commented
Une raison pour laquelle j'ai placé le code dans `beesdoo_account` : c'est une demande propre à Beescoop.
Néanmoins, avec la possibilité d'activer la fonctionnalité d'encodage de factures négatives, un autre client ayant `beesdoo_account` installé peut bénéficier de ce développement. 
Si d'autres clients souhaitent encoder des factures négatives, on externalisera et retravaillera le code dans `account_invoice_negative_amount` qui modifiera complètement le choix de design d'Odoo de ne pas autoriser cet encodage.