[ADD] beesdoo_shift: add periodicity field
beescoop/Obeesdoo pull request #207
Opened 2021-01-11 08:41 UTC by leeuwerck

to make generating shifts automatically more predictible

2021-01-12 11:05 UTC, remytms requested changes
Good job. Some change needed. :)

2021-01-12 11:05 UTC, remytms commented on beesdoo_shift/models/planning.py
> +    # There can be multiple planning templates defined. When generating shifts automatically, one template has to be selected. The sequence number of the previously used template is stored, so that i
Du coup tu peux retirer cette ligne. :)

2021-01-12 11:05 UTC, remytms commented on beesdoo_shift/models/planning.py
> +            periodicity = max(self.task_template_ids.mapped("day_nb_id.number"))
Du coup qu'on a mis une valeur par défaut pour périodicity. Je préfèrerais lever une erreur si periodicity ne contient pas la bonne valeur. On devrait être informé que la périodicity n'est pas bien configurée plutôt que de prendre une valeur qui n'a pas toujours de sens.

2021-01-12 11:05 UTC, remytms commented on beesdoo_shift/migrations/12.0.1.1.0/post-migrate.py
> +        "    ) as templates;")
Ok, c'est très bien en SQL aussi. :)

Sinon, il maque le caractère `\n` à la fin du fichier. Normalement un coup de black dessus devrait résoudre le problème.

Enfin, pour la mise en forme de la requête, l'utilisation de `"""` est bien pratique pour écrire une requête sur plusieurs lignes. :)

2021-01-13 11:47 UTC, remytms approved these changes
Good. :)

2021-07-13 07:22 UTC, vvrossem approved these changes

2021-07-22 17:27 UTC, merged