[IMP] make due date editable when a payment term is set
beescoop/Obeesdoo pull request #219
Opened 2021-03-05 16:04 UTC by houssine78

task explained [here](https://gestion.coopiteasy.be/web#id=6233&view_type=form&model=project.task&menu_id=338&action=479)

2021-03-08 09:23 UTC, vvrossem requested changes
LGTM but I would remove your funny muscles joke :D

2021-03-08 09:23 UTC, vvrossem commented on beesdoo_account/views/account_invoice.xml
> +                 So I used with my muscles with replace.
what muscles ? :trollface:

2021-03-08 09:23 UTC, vvrossem commented on beesdoo_account/views/account_invoice.xml
> +                <field name="date_due" attrs="{'readonly': [('state', 'in', ['open', 'in_payment', 'paid'])]}" force_save="1"/>
TIL : `force_save` send data to server for `readonly` fields

2021-03-19 13:16 UTC, robinkeunen reviewed
Shouldn't we move this in bees_custom? Would all supermarkets  want this?

2021-03-19 13:25 UTC, houssine78 commented
@robinkeunen I think that this will be useful for all the supermarket. But I'm ok with the proposition to put it in a stand alone module as it may interest other customers that have nothing to do with cooperative supermarket. It could also go to OCA

2021-03-19 13:54 UTC, robinkeunen commented
@houssine78 my last commit prevents odoo from resetting date_due to a computed value upon invoice validation (cf feedback from Virginie). 

However, I think it's not optimal since it prevents computation of date_due on a second change of payment_term_id. I don't think it's necessary to dig deeper in order to find a better way but that pushes the option to keep this out of beesdoo_account.

2021-03-19 14:33 UTC, houssine78 commented
@robinkeunen ok for me ! I can't approve my own PR so consider this comment as an approval.

2021-03-25 12:13 UTC, robinkeunen commented
closed in favor of https://github.com/coopiteasy/cie-custom/pull/17

2021-03-25 12:13 UTC, closed without merging