[IMP] add autoselect invoice when customer is company
beescoop/Obeesdoo pull request #228
Opened 2021-03-27 17:53 UTC by houssine78

Il est demande de sélectionner automatiquement la demande de facture lorsque le client est une société. Cela évite les oublis à la caisse.

2021-03-29 08:18 UTC, vvrossem requested changes
Peux-tu ajouter une explication dans `DESCRIPTION.rst` ? 
Aussi, est-ce que cette fonctionnalité convient à l'ensemble des supermarchés coopératifs ? Si oui, parfait. Si non, il vaut mieux créer un autre module `beesdoo_pos_auto_invoice`

2021-03-29 08:18 UTC, vvrossem commented on beesdoo_pos/static/src/js/beesdoo.js
> +            }
Attention, l'indentation est à corriger.
Peut-être aussi modifier ainsi :  `if (customer.is_company (...)` ?

2021-03-29 08:57 UTC, houssine78 commented
> 
> 
> Peux-tu ajouter une explication dans `DESCRIPTION.rst` ?
> Aussi, est-ce que cette fonctionnalité convient à l'ensemble des supermarchés coopératifs ? Si oui, parfait. Si non, il vaut mieux créer un autre module `beesdoo_pos_auto_invoice`

ok ! à mon avis oui car toutes entreprises ont besoin d'une facture

2021-04-07 17:57 UTC, houssine78 commented
@vvrossem done !

2021-04-09 09:38 UTC, robinkeunen approved these changes
Not an expert but looks good to me.

The CI is red but I suggest fixing it w/ PR #229 once the MeP is done.

2021-04-09 09:38 UTC, robinkeunen commented on beesdoo_pos/static/src/js/beesdoo.js
> +        		self.click_invoice();
There is still a problem of indentation here. I think (cf runbot) there is a mix of tabs and spaces.

2021-04-09 09:43 UTC, merged