[12.0][ADD] beesdoo_shift: parameters to _cron_send_weekly_emails
beescoop/Obeesdoo pull request #251
Opened 2021-07-14 13:44 UTC by vvrossem

## [Task](https://gestion.coopiteasy.be/web#id=6478&view_type=form&model=project.task&action=479)

This PR adds the following parameters to both record `ir_cron_send_weekly_emails` and its method `_cron_send_weekly_emails`:
- `notice=1`
- `period=7`

As the record `ir_cron_send_weekly_emails` is in a `<data noupdate="1">` element, administrators need to first delete the record, then update the module in order to recreate it (if `beesdoo_shift` is already installed on a database)

However, with the default values, this modification is backward compatible and will not raise any error if the delete-the-record-then-update-the-module action is not done.

2021-07-19 19:57 UTC, robinkeunen requested changes
As pointed, I think the PR should add a note in the readme.

I understand that another task is scheduled to make this configurable, if so, good for me when readme is added.

2021-07-19 19:57 UTC, robinkeunen commented on beesdoo_shift/data/cron.xml
>              <field name="interval_number">7</field>
I would add in the readme of the module that the interval number of the cron should be consistent with notice and period.

2021-07-20 07:55 UTC, vvrossem commented
README.rst updated with : 
```
- Configure "Send weekly shift summary" cron:

  - Its interval number (default = 7) should be consistent with notice (default = 1) and period (default = 7).
```

2021-07-20 08:10 UTC, robinkeunen approved these changes

2021-07-22 17:42 UTC, merged