add name and phone of referent on purchase order
beescoop/Obeesdoo pull request #27
Opened 2017-11-25 17:13 UTC by robinkeunen

ref https://odoo.bees-coop.be/web?#id=190&view_type=form&model=project.task&action=351&active_id=2

2017-11-26 13:10 UTC, tfrancoi requested changes

2017-11-26 13:10 UTC, tfrancoi commented on beesdoo_purchase/report/report_purchaseorder.xml
> +                <p t-if="o.partner_id.phone" t-field="o.partner_id.phone"/>
Je ne sais si qqun a testé ma ca ne me semble pas correct. le partner_id est le fournisseur.  je pense qu'ici le but c'est avoir le téléphone de la personne à la bees.

c'est plutot o.create_uid.partner_id.phone

2017-11-26 13:15 UTC, houssine78 commented on beesdoo_purchase/report/report_purchaseorder.xml
> +                <p t-if="o.partner_id.phone" t-field="o.partner_id.phone"/>
d'accord avec Thibault

2017-11-30 13:50 UTC, robinkeunen commented on beesdoo_purchase/report/report_purchaseorder.xml
> +                <p t-if="o.partner_id.phone" t-field="o.partner_id.phone"/>
_indeed_, mon mauvais.

2017-11-30 14:07 UTC, robinkeunen commented
cf https://github.com/beescoop/Obeesdoo/pull/30

2017-11-30 14:07 UTC, closed without merging