[FIX] beesdoo_product: fix computed field total_with_vat
beescoop/Obeesdoo pull request #281
Opened 2022-02-24 13:22 UTC by tfrancoi

- Don't raise ValidationError in stored computed field it may crash at module installation
- Handle case were deposit is tax excluded, exclude them from the tax computation
  and include them at the end in the deposit field

2022-02-24 13:24 UTC, tfrancoi commented
Decide what we do in case of taxe included and excluded ?
- Let 0.0 and user has to guess
- Log the info : the user won't see it
- Display a nice message with a new computed : More work

2022-02-24 14:17 UTC, robinkeunen commented
Decision : 
- Ajouter un message à partir d'un champ calculé "ne peut pas être imprimé"

2022-02-24 14:19 UTC, robinkeunen requested changes
Ajouter un message à partir d'un champ calculé "ne peut pas être imprimé".

2022-04-01 14:20 UTC, polchampion commented
Successfully tested - excluded-tax deposits are properly handled in SOs and on POS orders and tickets.

2022-06-23 14:24 UTC, robinkeunen approved these changes

2022-06-23 15:12 UTC, remytms approved these changes
LGTM

2022-06-23 15:15 UTC, merged