[IMP] beesdoo_product: make suggested price rounding configurable
beescoop/Obeesdoo pull request #282
Opened 2022-02-24 13:58 UTC by tfrancoi

Allow to configure the rounding of suggested price
choose the method and the precision of the rounding on the category

2022-02-24 14:26 UTC, robinkeunen approved these changes
Small comments. Tests would be nice, we'll do it when splitting the module and move it to the oca.

2022-02-24 14:26 UTC, robinkeunen commented on beesdoo_product/models/beesdoo_product.py
> +        # Keep default value on the field to make it explicit to the end user
Can't we rather set the rounding method and precision to required ?

2022-02-25 13:14 UTC, robinkeunen requested changes

2022-02-25 13:14 UTC, robinkeunen commented on beesdoo_product/models/beesdoo_product.py
> +        # Keep default value on the field to make it explicit to the end user
Can't we rather set the rounding method and precision to required ?

2022-03-11 10:45 UTC, polchampion commented
@robinkeunen Testé sur oufticoop-test et OK

2022-03-11 15:00 UTC, robinkeunen approved these changes

2022-03-11 15:01 UTC, merged

2022-03-25 17:20 UTC, vdewulf commented
Pol has documented this new feature here:
https://doc.it4socialeconomy.org/books/configurations/page/ajouter-sur-la-fiche-article-les-labels-prix-suggere-et-dangerosite