[ADD] beesdoo_shift_welcome_screen: new module
beescoop/Obeesdoo pull request #288
Opened 2022-02-24 15:06 UTC by tfrancoi

Add a module for cooperator welcome screen

- Scan your member card
- See if you can shop
- See your counter and status

- See your eater
- See your next shift

2022-02-24 16:03 UTC, robinkeunen requested changes

2022-02-24 16:03 UTC, robinkeunen commented on beesdoo_shift_welcome_screen/models/welcome.py
> +            self.message = "more then one member found with this barcode"
Shouldn't all these messages be translated ?

2022-02-24 16:03 UTC, robinkeunen commented on beesdoo_shift_welcome_screen/models/welcome.py
> +    # can_shop = fields.Boolean(related='partner_id.can_shop', readonly=True)
remove this comment ?

2022-02-24 16:03 UTC, robinkeunen commented on beesdoo_shift_welcome_screen/models/welcome.py
> +                ("start_time", ">", now.strftime("%Y-%m-%d %H:%M:%S")),
Why not use a datetime type ? Des restes de la v9.

2022-03-29 09:49 UTC, vdewulf commented
Welcome Screen tested on oufticoop.test.coopiteasy.be
New user created "welcome@oufticoop.be" with the right to "Shifts - Planning" (in order to see the Menu).

Connected as welcome user.
New Menu "Shift Welcome". Cf. screenshot
- TO TEST : scan a barcode.
I just entered a barcode manually in the Cooperator field, it does not work.
To be tested with a real scanner and a card.

- Manual selection
I selected a coop in the list (regular worker).
The status "Can shop" is displayed, his name, his counter and the next shifts (the next generated in the system it seems).
When the person in the list is an "eater", the name of the worke
![welcome_screen_empty](https://user-images.githubusercontent.com/27895270/160584519-db2c1ed8-2f0d-4760-97fd-c80e81bce1f7.png)
r is displayed.
If the person has some eaters, their name is also di
![welcome_screen_can_shop](https://user-images.githubusercontent.com/27895270/160584516-e48bb92f-959f-4b8e-8eac-a3dc697f9a12.png)
splayed.
![welcome_screen_cannot_shop](https://user-images.githubusercontent.com/27895270/160584496-17d4efb9-bf04-4d1e-8a5b-0b6b48515bce.png)

Conclusion : it works fine but we need to test the real "scan".
I edited the translation, cf. PO file for French BE (in CIE task because po file not supported in github)

2022-03-29 13:29 UTC, polchampion commented
Welcome Screen tested on bees.test.coopiteasy.be
Connected with admin (in order to see the Menu).
Tested with the scan for existing user.

Scan needs to be set up to be used aside of keyboard because it only works if the language is en_US. I changed my computer's language to en_US for it to work but then I can't use the keyboard in French (this is an unrelated issue).

Note : when you select a cooperator in the list manually, then scan a barcode, it doesn't work (you need to click away first) : 
![screenshot-bees test coopiteasy be-2022 03 29-15_26_51](https://user-images.githubusercontent.com/92738727/160621969-22f9ace0-2a2a-41fa-b47a-bd8b5f980b2a.png)

2022-03-29 13:33 UTC, polchampion commented
@robinkeunen Tested (it works) and I left a suggestion above.

2022-03-29 13:33 UTC, robinkeunen approved these changes

2022-03-29 15:26 UTC, merged