[ADD] beesdoo_shift_swap, beesdoo_website_shift_swap
beescoop/Obeesdoo pull request #309
Opened 2022-02-28 13:10 UTC by MatteoLdx

Add modules for the beesdoo shift exchange system

2022-03-03 16:08 UTC, carmenbianca commented
@MatteoLdx Small warning: This is a _lot_ of commits, which makes it more difficult to review and merge. Where possible, consider squashing commits before requesting a review, or splitting the PR up into separate PRs. If you need help with the Git magic required to make those things happen, always feel free to ask :)

2022-03-15 14:02 UTC, carmenbianca requested changes, later dismissed
[09f42bc](https://github.com/beescoop/Obeesdoo/pull/309/commits/09f42bc096f885d452f543aeab4a3592f2ca1199) removes some stuff to do with periodicity that is immediately re-introduced in the next commit [6f65731](https://github.com/beescoop/Obeesdoo/pull/309/commits/6f65731bbeedfb636aea2095d6c9f53869424b44). This is weird. [6f65731](https://github.com/beescoop/Obeesdoo/pull/309/commits/6f65731bbeedfb636aea2095d6c9f53869424b44) should probably be dropped, and [09f42bc](https://github.com/beescoop/Obeesdoo/pull/309/commits/09f42bc096f885d452f543aeab4a3592f2ca1199) should be edited to not remove periodicity stuff.

[2ecf7c8](https://github.com/beescoop/Obeesdoo/pull/309/commits/2ecf7c812fbc3b7945ece90d9b580b5479bc49dc) suspiciously also removes periodicity stuff, and [b1c33e5](https://github.com/beescoop/Obeesdoo/pull/309/commits/b1c33e54287b776fcde00bf5837fb4c14667d600) does not correctly revert everything.

2022-03-15 14:02 UTC, carmenbianca commented on beesdoo_shift/models/planning.py
> -        return date + timedelta(days=periodicity)
This should NOT be changed by this commit.

2022-03-15 14:23 UTC, carmenbianca commented on beesdoo_website_shift/controllers/main.py
> -
Is this correctly deleted?

2022-06-16 16:46 UTC, vdewulf commented
@MatteoLdx J'ai testé sur bees.test.coopiteasy.be le scénario suivant :
- avec un travailleur régulier en statut "Alerte", je me connecte au portail
- je m'inscris à un shift de compensation (pop up de confirmation - message vert indiquant que ça a marché) J'ai trouvé que c'était très lent après avoir cliquer sur "Sinscrire" dans le pop up : plus de 5 secondes avant qu'il se passe qqch.
- retour sur la page my/shifts : le shift est bien dans la liste des futurs shifts
- en back end je vérifie et le shift est bien encodé avec la personne inscrite dessus, le type de shift "compensation" est sélectionné
- je reviens dans la fenêtre du portail et je me désinscris du shift : pop up de confirmation (ok) mais ensuite, je suis reviens sur la page /my/shift sans message vert d'info. Est-ce un oubli ? J'ai trouvé aussi que ça "tournait" longtemps avant que le pop up disparaisse.
- cela dit, le prochain shift n'est plus celui auquel j'étais inscrite, donc ça a marché.
- il n'est pas possible de se désinscrire des autres shifts (réguliers)

- login avec un travailleur volant en statut A jour (j'ai bidouillé le compteur de mon travailleur volant test pour le remettre à jour et rester logguée) ==> le bouton pour s'inscrire à un shift de compensation n'apparait pas.
- si le statut est "alerte rouge" => il est possible de s'inscrire à un shift de compensation. C'est bien voulu ?
- si le statut est "en pause" => il est possible de s'inscrire aussi. C'est bien voulu ?

2022-06-16 16:50 UTC, vdewulf commented
@MatteoLdx pour info c'est documenté ici : https://doc.it4socialeconomy.org/books/application-gestion-des-shifts/page/acceder-aux-creneaux-et-shifts-sur-son-espace-personnel

2022-06-17 07:59 UTC, MatteoLdx commented
@vdewulf 
- Pour les popups de confirmation ça a été corrigé mais pas encore sur le serveur de test
- Pour les deux dernières questions sur les statuts, si ce sont des utilisateurs réguliers c'est voulu, s'ils sont volants ça ne l'est pas

2022-06-17 09:04 UTC, vdewulf commented
@MatteoLdx je n'ai testé qu'avec des réguliers donc c'est bien ok :) Je n'ai rien testé avec les volants mais j'imagine que Pol l'avait fait. Dis moi si besoin de tester plus :)

2022-06-20 08:54 UTC, remytms approved these changes
Good for now. :)

2022-06-20 11:46 UTC, remytms commented on beesdoo_shift/models/res_partner.py
> +        nb_days = 28 * regular_next_shift_limit
In a general comment, we should improve this and not hardcode `28` anymore. But it's not related to this PR.

2022-06-20 12:23 UTC, remytms commented on beesdoo_website_shift/static/src/js/script.js
> +odoo.define("beesdoo_website_shift.script", function (require) {
@MatteoLdx Un small comment here to explain what does this javascript code would be wonderfull. :)

2022-06-20 12:25 UTC, remytms commented on beesdoo_website_shift_swap/__manifest__.py
> +        # 'security/ir.model.access.csv',
@MatteoLdx This should be fixed.

2022-06-20 12:27 UTC, remytms commented on beesdoo_website_shift_swap/demo/demo.xml
> +        <!--  -->
@MatteoLdx This should be cleaned.

2022-06-20 12:30 UTC, remytms commented on beesdoo_worker_status_shift_swap/models/task.py
> +            #    .get("irregular_absence_counter", 0)
@MatteoLdx This should be cleaned.

2022-06-20 12:30 UTC, remytms approved these changes
Minor changes that can be performed later.

2022-06-20 12:34 UTC, remytms commented
/ocabot merge nobumps

2022-06-20 12:35 UTC, merged