[IMP] Change validating sheets warning
beescoop/Obeesdoo pull request #317
Opened 2022-03-13 15:48 UTC by MatteoLdx

Don't display the warning when validating attendance sheets if there's no absents

2022-03-14 14:09 UTC, robinkeunen requested changes, later dismissed

2022-03-14 14:09 UTC, robinkeunen commented on beesdoo_shift_attendance/models/attendance_sheet.py
> +    absents = fields.Boolean(
Rather `missing_worker` (+ compute function)

2022-03-14 14:09 UTC, robinkeunen commented on beesdoo_shift_attendance/models/attendance_sheet.py
> +    absents = fields.Boolean(
`has_missing_worker`

2022-03-14 14:09 UTC, robinkeunen commented on beesdoo_shift_attendance/models/attendance_sheet.py
> +
```suggestion
    @api.depends("expected_shift_ids", "added_shift_ids")
    def _compute_absents(self):
        for rec in self:
            if any((s.state != 'done' for s in rec.expected_shift_ids)):
                rec.absents = True
                continue 
            if any((s.state != 'done' for s in rec.added_shift_ids)):
                rec.absents = True
                continue
```

2022-03-30 07:49 UTC, remytms reviewed
@MatteoLdx LGTM, but squash your commits. :)

2022-03-30 08:07 UTC, remytms approved these changes
OK

2022-04-14 16:56 UTC, merged