Change the beesdoo_print_label module
beescoop/Obeesdoo pull request #431
Opened 2022-07-12 16:30 UTC by FlyearthR

## Description
Change the template to be more readable.

## Odoo task (if applicable)

## Checklist before approval

- [X] Tests are present (or not needed).
- [X] Credits/copyright have been changed correctly.
- [ ] Change log snippet is present. (?)

2022-07-27 15:29 UTC, robinkeunen requested changes
Looks good except for a small comment. I'll deploy this so that Virginie can test. Can you also check the precommit tests ?

2022-07-27 15:29 UTC, robinkeunen commented on beesdoo_print_label/__manifest__.py
> +    "application": True,
An application covers a new functional scope and gets its entry point in the menu. This is not an application but only an addon.

2022-08-10 07:52 UTC, vdewulf commented
@robinkeunen 
Tested on bees-test
See screenshot.
The product name is larger but it's quickly truncated (the text goes on a second line and we see the top of the letters only). I don't know what we can do about it... It seems to have some space above the first line, maybe possible to get the name displayed in big letter on 2 full lines? This will need to be discussed with users.
The "fournisseur" text is removed (but the provider is still displayed and is larger) : ok
The "consigne" part is moved lower : ok
The "poids" and "prix/l ou prix/kg" is removed : ok
The price per unit: the "/[display_unit.name] is not added : NOT OK

[test_etiquettes.pdf](https://github.com/beescoop/Obeesdoo/files/9297921/test_etiquettes.pdf)

Could you correct the NOT OK line (about the name, let's keep it like this and discuss with users) before next intercoop meeting so that I can send it to the participants beforehand?
Thanks!

2022-08-10 13:11 UTC, vdewulf commented
@robinkeunen 
I discussed with Matthieu (bloum), we think that the product name should be on 2 lines (and "big letters"). If you have the courage to take this :)
Maybe with @remytms's help?

2022-08-17 14:38 UTC, robinkeunen commented
Closing in favor of https://github.com/beescoop/Obeesdoo/pull/445

2022-08-17 14:38 UTC, closed without merging

2022-08-25 08:55 UTC, carmenbianca commented
@robinkeunen this PR is still enabled on test. #445 is not. please look at this when you're back.