Add the stock_move_view_order module
beescoop/Obeesdoo pull request #433
Opened 2022-07-12 16:35 UTC by FlyearthR

## Description
Inverse the default view order of the stock moves

## Odoo task (if applicable)

## Checklist before approval

- [X] Tests are present (or not needed).
- [X] Credits/copyright have been changed correctly.
- [ ] (?)Change log snippet is present.
- [X] (If a new module) Moving this to OCA has been considered.

2022-07-27 15:51 UTC, robinkeunen requested changes
A few easy feedbacks but it otherwise looks good. I'll deploy it for Virginie.

2022-07-27 15:51 UTC, robinkeunen commented on stock_move_view_order/__init__.py
> +#coding:utf-8
not needed in python 3

2022-07-27 15:51 UTC, robinkeunen commented on stock_move_view_order/__manifest__.py
> +
No need for these empty lines.

2022-07-27 15:51 UTC, robinkeunen commented on stock_move_view_order/models/__init__.py
> +from . import models
missing new line

2022-07-27 15:51 UTC, robinkeunen commented on stock_move_view_order/__manifest__.py
> +    'application': True,
This is not an application either :-)

2022-07-27 15:51 UTC, robinkeunen commented on stock_move_view_order/models/models.py
> +
This file is not needed since you don't add or remove anything.

2022-07-27 15:51 UTC, robinkeunen commented on stock_move_view_order/__manifest__.py
> +        "views/inhereted_view_from_stock_move_line.xml"
A better file name would be `stock_move_line_views.xml`

2022-08-10 07:58 UTC, vdewulf commented
@robinkeunen 
I installed stock_move_view_order on vervicoop.test.
On product, click on "mouvements de stock", the lines are displayed with the recent records on top.
See screenshot with comparison prod.test on same product
![image](https://user-images.githubusercontent.com/27895270/183847127-69b82096-1fd1-494e-a7c8-f986a7503e8e.png)
This can be deployed on next release.
You can add the deploy note on T5584 in our Odoo project.

2022-08-11 15:25 UTC, robinkeunen commented
closed in favor of https://github.com/beescoop/Obeesdoo/pull/444

2022-08-11 15:25 UTC, closed without merging