12.0 rename beesdoo pos reporting
beescoop/Obeesdoo pull request #468
Opened 2022-10-31 15:40 UTC by victor-champonnois

## Description
fix https://github.com/beescoop/Obeesdoo/issues/346

## Odoo task (if applicable)

## Checklist before approval

- [ ] Tests are present (or not needed).
- [ ] Credits/copyright have been changed correctly.
- [ ] Change log snippet is present.
- [ ] (If a new module) Moving this to OCA has been considered.

2022-11-01 10:32 UTC, robinkeunen approved these changes
Looks good but could it be moved to the oca directly?

2022-11-01 10:42 UTC, victor-champonnois commented
@robinkeunen according to https://user-images.githubusercontent.com/17589077/149927982-58f1b329-9d15-48d3-b331-77741f7c2e87.png it should be moved to cie-pos, plans have changed ?

2022-11-02 10:58 UTC, robinkeunen commented
My point of view has changed now yes. Maybe @legalsylvain could tell us whether he thinks `pos_order_count_store` would be welcome on oca/pos ?

The description.rst : 

> Store pos_order_count to improve reporting.

2022-11-02 12:01 UTC, legalsylvain reviewed
Hi. 

Thanks for the ping. I think that the module ``pos_order_count_store`` has its place under OCA umbrella. (generic and add features), as far as the "update" question is OK.

I think that if yes, you should add a pre-init-hook script to compute by SQL the stored field.
Otherwise, installing this module on existing databases (the GRAP one, for instance) will take hours for sure.

2022-11-02 12:01 UTC, legalsylvain commented on pos_order_count_store/models/res_partner.py
> +    pos_order_count = fields.Integer(store=True)
I fear that if we make an update all, the update of point_of_sale module drop the column, and then, the update of the pos_order_count_store module recompute it. Am I wrong ?

2022-11-02 12:01 UTC, legalsylvain commented on pos_order_count_store/models/res_partner.py
> +    pos_order_count = fields.Integer(store=True)
(I remember that I developed one time a module store = True -> store =False, and that was problematic.

2022-11-03 09:06 UTC, victor-champonnois commented on pos_order_count_store/models/res_partner.py
> +    pos_order_count = fields.Integer(store=True)
Thank you for your reply

> I fear that if we make an update all, the update of point_of_sale module drop the column, and then, the update of the pos_order_count_store module recompute it. Am I wrong ?

It's not what I observe, when updating point_of_sale (and then pos_order_count_store), the field was never recomputed.

Noted for the SQL Query in pre-init hook !

2022-11-07 07:50 UTC, victor-champonnois commented
- I added the pre_init_hook
- @polchampion OK to test on coopeco-test and lesptitpots-test. To be tested : "Store pos_order_count to improve reporting." (check that the number of pos_order per partner is OK)

2022-11-07 10:16 UTC, robinkeunen requested changes
Thx for the pre-init hook 👍 Can you rebase, squash and move the module to oca/pos ?

2022-11-14 16:54 UTC, robinkeunen commented
/ocabot rebase

2022-11-15 13:08 UTC, victor-champonnois commented
/ocabot rebase

2022-11-15 13:09 UTC, victor-champonnois commented
@robinkeunen LGTM, should be merged for next MEP, so that pos_counter_store is installed

2022-11-15 13:11 UTC, victor-champonnois commented
@robinkeunen can you approve the PR ?

2022-11-15 13:19 UTC, robinkeunen approved these changes

2022-11-15 14:41 UTC, merged

2022-11-21 15:55 UTC, polchampion commented
@victor-champonnois Sucessfully tested on coopeco-test : number of pos orders for one partner seems right (smart button on profile + pos order dynamic table view + filter on all orders for that partner.