[16.0] [MIG] member_card
beescoop/Obeesdoo pull request #522
Opened 2023-08-03 14:44 UTC by victor-champonnois

task : https://gestion.coopiteasy.be/web#id=10992&action=475&active_id=492&model=project.task&view_type=form&menu_id=

2023-09-05 15:15 UTC, carmenbianca requested changes
Mostly LGTM, but some criticisms.

Can we try to make the compute method work?

2023-09-05 15:15 UTC, carmenbianca commented on member_card/demo/cooperators.xml
> -        <field name="customer" eval="True" />
Why? Was this field removed?

2023-09-05 15:15 UTC, carmenbianca commented on member_card/report/member_card_template.xml
> +        <field name="print_report_name">'Member Card'</field>
This strikes me as odd.

2023-09-05 15:15 UTC, carmenbianca commented on member_card/models/partner.py
> +        self.barcode = card.barcode
I am not certain I like this solution.

1. If we're going to write the barcode string on the partner, we should do it in `member.card`'s create method, not here.
2. I think we should research a way to make the compute method work.

In any case, making `member.card` readonly seems like a fairly sound idea.

2023-09-05 15:15 UTC, carmenbianca commented on member_card/views/member_card.xml
> +        </record>
dedent ;)

2023-09-07 09:01 UTC, victor-champonnois commented on member_card/demo/cooperators.xml
> -        <field name="customer" eval="True" />
Because customer does not exist in 13

2023-09-08 13:23 UTC, victor-champonnois commented
Note : we spent some time investigating with Hugues on how to make the compute method work. It's likely to be a problem related to multi-company, and the fact that the original barcode field (in odoo/base) is company_dependent. 
If we use a "new"  barcode field (with another name) that is not overiding the original barcode field it works well.
We tried adding `  @api.depends_context('company')`   on the compute method, and `company_dependent=False` on the parameters. But none works. 
To be continued...

2023-09-11 07:46 UTC, victor-champonnois commented
@carmenbianca @huguesdk How do we move on with this ? Should we give up trying to make the compute method work and do it another way ?

2023-09-13 14:04 UTC, huguesdk commented
i think we should first make some tests with a minimal module to understand how we’re supposed to do it (i did something similar to test out how to do company-dependent related fields for cooperator).

2023-09-29 15:19 UTC, carmenbianca commented
I'm making some progress on this, but I am (partially) blocked by https://github.com/odoo/odoo/issues/137141

2023-09-29 15:40 UTC, carmenbianca commented
Reverted the workaround, added a fix. Setting `company_dependent=False` was enough, in spite of your prior research. Not sure how that went wrong.

Awaiting review.

2023-12-19 16:43 UTC, robinkeunen requested changes
We're getting there

2023-12-19 16:43 UTC, robinkeunen commented on member_card/demo/cooperators.xml
>      <record id="res_partner_cooperator_1_demo" model="res.partner">
We should use demo data from the standard modules rather than adding new fake partners.

2023-12-19 16:43 UTC, robinkeunen commented on member_card/models/partner.py
> +    # TODO: Remove after https://github.com/odoo/odoo/issues/137141 is resolved.
It is resolved.

2023-12-20 15:59 UTC, robinkeunen commented on member_card/report/member_card_template.xml
> +        <field name="print_report_name">'Member Card'</field>
it is the way

2023-12-20 16:00 UTC, robinkeunen approved these changes

2024-01-04 13:34 UTC, polchampion commented
Functional test on 04/01/2023 and 12/01/2024 on [16-test-member-card](https://odoo16.main.test.srv.coopiteasy.be/web?db=16-test-member-card): 
@victor-champonnois @robinkeunen I improved the list of features a tad:

- [x] Adds a member_card_template view and print option on partner
- [x] Adds a "Member card" tab on the partner with a button to create a new member card
- [x] The partner's card and barcode history is visible in the member card tab
- [x] Creating a card generates a barcode, witch is then displayed on the member card
- [x] The "Force Barcode" option allows to set a specific barcode instead
- [x] A partner's barcode is computed from the last active member card 
- [x] Adds a field `member_card_logo` on the company allowing to upload an image
- [x] The card template displays the `member_card_logo`  image
- [x] A boolean "Print Member card?" allows to flag partners for whom you need to print new cards.
- [x] The wizards "Request member card printing" and "Set member card as printed" allow to mass check and uncheck the "Print Member Card?" flag.
- [x] If the point of sale is installed, the generated barcode matches customer pattern rule.

2024-01-11 16:21 UTC, robinkeunen commented
@carmenbianca ready for another review

2024-01-12 13:22 UTC, polchampion commented
@robinkeunen functional tests ok, I updated my previous post!

2024-01-23 13:39 UTC, huguesdk approved these changes
lgtm. i squashed the migration-related commits together.

2024-01-24 10:34 UTC, robinkeunen commented
/ocabot merge nobump

2024-01-24 10:39 UTC, merged