[IMP] Supercoop resigning
beescoop/Obeesdoo pull request #65
Opened 2019-03-20 11:30 UTC by nicolasj77

Suppression des shifts (dans worker informations) et des shifts futurs pour les super coopérateurs.

Dans task.py je me suis permis de modifier cette ligne
date_domain = [('worker_id', 'in', worker_ids), ('start_time', '>=', today)]
Car j'avais l'impression que 'worker_id', 'in', worker_ids faisait double emploi/

et ici :
to_unsubscribe_super_coop.write({'super_coop_id': False,
'is_regular': False}) --> je l'ai indiqué comme pour faire dans le code des worker_id, est-ce pertinent ?

2019-03-21 09:54 UTC, robinkeunen reviewed
Quelque remarques cosmétiques, le reste m'a l'air bon mais je pense que c'est pas mal que Thibault ou Rémy repassent dessus.

2019-03-21 09:54 UTC, robinkeunen commented on beesdoo_shift/models/task.py
> +        # If worker is Super cooperative, remove it from planning
super cooperat**or**\*

2019-03-21 09:54 UTC, robinkeunen commented on beesdoo_shift/models/task.py
> +        super_coop_id = self.env['res.users'].search(
super_coop_id**s**\* et couper la ligne comme Rémy l'a suggéré dans l'autre PR :-)

2019-03-21 09:54 UTC, robinkeunen commented on beesdoo_shift/models/task.py
> +            to_unsubscribe_super_coop = self.search([('super_coop_id', 'in',
Pareil ici, ce qui nous importe, c'est la lisibilité du code. Ici, le domaine sur une seule ligne le rend beaucoup plus lisible.
```python
to_unsubscribe_super_coop = self.search(
    [('super_coop_id', 'in', super_coop_id)] + date_domain
)
```

2019-03-21 09:54 UTC, robinkeunen commented on beesdoo_shift/wizard/subscribe.py
> +            'resigning': self.resigning,
<3

2019-03-23 08:17 UTC, nicolasj77 commented on beesdoo_shift/models/task.py
> +        # If worker is Super cooperative, remove it from planning
?

2019-03-23 08:20 UTC, nicolasj77 commented on beesdoo_shift/models/task.py
> +        # If worker is Super cooperative, remove it from planning
ok :) done

2019-03-23 08:34 UTC, nicolasj77 commented on beesdoo_shift/models/task.py
> +            to_unsubscribe_super_coop = self.search([('super_coop_id', 'in',
Done

2019-03-23 08:36 UTC, nicolasj77 commented on beesdoo_shift/models/task.py
> +        super_coop_id = self.env['res.users'].search(
La coupure m'a l'air ok ici, que suggères-tu ?

2019-04-02 06:40 UTC, nicolasj77 commented
Je peux merger ?

2019-04-02 06:49 UTC, remytms commented
Hum, attends que j'arrive au bureau. J'ai l'impression qu'il y a un nouveau commit qui c'est rajouté.

2019-04-02 08:31 UTC, remytms commented
Je regarde ça cette aprèm. Pour moi le commit ff9cb61 ne devrait pas être là.

2019-04-02 15:03 UTC, remytms requested changes
Some changes needed.

2019-04-02 15:03 UTC, remytms commented on beesdoo_shift/models/task.py
> +        date_domain = [('start_time', '>=', today)]
Tu peux carrément supprimer la ligne à la place de la mettre en commentaire. :)

Git nous permettra de revenir en arrière si besoin, mais ce ne sera pas le cas. ;)

2019-04-02 15:03 UTC, remytms commented on beesdoo_shift/views/task.xml
> +                            <field name="replaced_id" attrs="{'invisible': [('is_regular', '!=', True)]}"/>
@nicolasj77 Attention ! Ici il y a un problème à mon avis.

2019-04-02 23:14 UTC, remytms approved these changes

2019-04-02 23:16 UTC, remytms commented
@nicolasj77 Yeah ! You made it right ! :D You're gonna be a git man ! :D

2019-04-02 23:18 UTC, remytms commented
@nicolasj77 To be commit perfect, you can squash all your commits into one. :) But it can be merge like this if you don't have time. :)

2019-04-03 15:13 UTC, merged