[IMP] Not suscribe shift message
beescoop/Obeesdoo pull request #67
Opened 2019-04-01 12:56 UTC by nicolasj77

Message pour les parts A sans régime de travail et fix pour les regular workers qui n'ont pas d'inscription à des shifts.

2019-04-01 14:20 UTC, tfrancoi commented
i would not rename partner_firstname since the goal was to shadow the shitty module from OCA but if you really want to, at least change the dependency in beesdoo_base: https://github.com/beescoop/Obeesdoo/blob/9.0/beesdoo_base/__openerp__.py#L18

2019-04-01 14:34 UTC, remytms commented
@tfrancoi,

Yes, it was just a branching issue from @nicolasj77. I'm checking that with him. This PR should only contain this commit ecf42aa.

Thank for your attention. :)

2019-04-01 14:37 UTC, remytms requested changes
I will clean up the commit b6dd0fa, as it contain a lot of unneeded indentation changes.

2019-04-04 13:18 UTC, remytms commented
@nicolasj77 

Merci pour cette belle PR. :)

Il y avait juste beaucoup de réindentation inutile dans le fichier des templates. J'ai donc retravaillé ton commit pour mettre tout ça au propre.

J'en ai profité pour apporter quelques petites modifications mineures.

2019-04-04 13:22 UTC, remytms commented
It's merged ! See commit 1d53e2b71a94db14984f171a195e57a032866cd4

2019-04-04 13:22 UTC, closed without merging